### ISSUE TITLE
NTMLv2

### ISSUE THREAD

**Issue by nicklasb** [trustrachel/python-ntlm3#10]
Hi,
I am wondering if you are considering NTLMv2 support?

PyAuthenNTLM2 is what seems like a dormant python2.x-only library that claims v2 support, I am thinking inspiration from that project could be a way to go places for python-ntlm3?

A working and native NTMLvX library for Python 3 would be a really great thing.

**Comment by trustrachel** [comment]
Oh cool, thank you for the pointer! I'll take a look. I agree this would be really useful.

Do you know for sure that it doesn't support v2, by chance? I saw some code in there that claims to handle v2, but the codebase is in such awful shape, it's hard to tell if it actually works or not. (Cleanup is on my list of things to do.)

I happily take pull requests, so if you feel like tackling it, that would be great.

**Comment by nicklasb** [comment]
No, what I was saying was that claims to support NTLMv2, not that it doesn't.
I would be glad to help out, and I actually do have time for it, however I don't know *anything* about the technicalities about NTLMv2.
To be completely honest, I have interests in getting several python projects going, so i'll have to review my priorities. However, even though Kerberos has replace NTLM in general it does seem like there still are several NTLMv2 use cases.  

Complete native Python3 support for all those authentication methods would make my application able to confidently wade through whatever network was presented to it. :-)

**Comment by trustrachel** [comment]
Sadly, I don't know much about the technicalities, either. I just ported the library to 3. :/  I do have an Exchange server here at work, so I can test solutions.

However, you raise a good point. Let me confirm if the library supports (or not) NTMLv2. I'll hit up the exchange people here at work and see if they'll help me out with a test.

**Comment by nicklasb** [comment]
If you could do that, it would be great. I could probably be more helpful with a 2 to 3 conversion as well. Anyway, I am making a BPM system(anything but similar to the others so far :-) ), so I have good reason to set up an exchange server here for more long-term testing against Microsoft platforms, but not until a month from now, at the earliest.

It would be great if one could record a couple of typical successful and non-successful conversations between the PyAuthenNTLM2 and the exchange server, and then make a mock that tells when something changed, that way one could perhaps  be able make to make the porting a bit easier.

**Comment by trustrachel** [comment]
Thanks, that's a great idea. I'm hoping I can do something with Appveyor so I can tie tests directly into it - it looks like they have IIS installed on their boxes. The ideal case would be to just use that for live testing.  

But the canned responses is a good idea, too, and would be good to have in any case.

**Comment by nicklasb** [comment]
Hi, just checking in, have you had any time for this yet? 
I will set up an exchange server here next week for the emailing stuff, thinking of that I perhaps could try and test the NTLMV2-claims of PyAuthenNTLM2 out as well.

**Comment by nicklasb** [comment]
BTW, I have no grand Ideas about the perfect NTLMvX-library, I thinking about adding the v2 support to python-ntlm3 in some way that works, nothing fancy. 
After all, NTLM is legacy technology.  pyexchange, on the other hand..

**Comment by trustrachel** [comment]
I'm real sorry about the delay, I've got a backlog of stuff to do, and am planning to tackle it all at PyCon. Thanks for being patient. :)

**Comment by trustrachel** [comment]
BTW, if you're going to be there, I'm happy to meet up and chat about it!

**Comment by nicklasb** [comment]
No problem. 

Tomorrow I will start put up an exchange server an try to fetch and send some e-mail.
Perhaps you will see some pull requests from me in week or so.
 
I sure would, if my boss(me, that is) would let me go as far as to Toronto on something that fun.  :-)
Perhaps next year.

**Comment by trustrachel** [comment]
Awesome, sounds great. I'm here at PyCon, so I'm happy to see any pull requests.

**Comment by nicklasb** [comment]
Oh, that was with regards to pyexhange, I have written about what I have been doing in the [pyexchange issue.](https://github.com/linkedin/pyexchange/issues/44)

**Comment by nicklasb** [comment]
Am jealous, BTW. :-)

**Comment by mragaei** [comment]
Hello @trustrachel,

Many thanks for your efforts but I believe NTLMv2 is not supported in this package given that you just ported it from Python2 to Python3 and that the same issue is reported and still "open" in the original repository:

https://github.com/mullender/python-ntlm/issues/47

You may want to reopen this one accordingly.
We really need to have NTLMv2 supported as many projects are depending on it (requests-ntlm is one of them as you may already know).

**Comment by jborean93** [comment]
I think we should look at re-opening this. I am doing some work with the library and have a working implementation of NTLMv2 and will submit a pull request sometime soon. The signing and encryption of the messages are still outstanding and that will require more work on top of this but hopefully this can give us a working platform to go on.
